import type { Metadata } from 'next';
import './globals.css';
import { fetchMoviesList } from '../utils/axios';
import { sortValue } from './components/SortControl/SortControl';
import HomePage from './components/HomePage/HomePage';

export interface MovieInfo {
  /** Movie id*/
  id: string;
  /** Image url*/
  poster_path: string;
  /**Movie title */
  title: string;
  /**Movie release year */
  release_date: string;
  /**Movie janres list */
  genres: string[];
  /**Movie vote_average */
  vote_average: string;
  /**Movie length */
  runtime: string;
  /**Movie overview */
  overview: string;
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function InitialPage({ searchParams }: {searchParams: { [key: string]: string }, }) {

  let query = searchParams.query || '';
  let sortBy = searchParams.sortBy as sortValue || sortValue.default;
  let genre = searchParams.genre || 'All';
  let initialList = [] as MovieInfo[];

  initialList = await fetchMoviesList(sortBy, query, genre);

  return (
    <>
      <HomePage initialList={initialList} />
    </>
  )
}
